### ISSUE TITLE
Material - Icon Hover Bug

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#101]
https://gyazo.com/fac608fa3213e84afebf6a64a04e96e2

The user has reported that when hovering over the icons which are located on the post editor. It causes sort of a double vision of each button.

Ticket: https://admin.audent.io/tickets/7901

**Comment by Ian-Hitt** [comment]
@dprock I believe this is not a bug in material, but rather an incompatibility for a third party bbcode add-on.

**Comment by dprock** [comment]
@Ian-Hitt I thought the same thing, forgot to place a comment here.
