### ISSUE TITLE
Material - Sometimes following and followers are mixed up

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#102]
![followers_bug](https://cloud.githubusercontent.com/assets/26636634/25345013/559ef268-2903-11e7-86f4-b22f77dfe889.png)

If I'm following 0 people and I've got 23 followers then the avatars of the 23 followers are **sometimes** listed under the tab that says "FOLLOWING 0" instead of the tab that says "FOLLOWERS 23". I say sometimes because I'm not able to reproduce this issue on every user profile.

I first seen this issue with Material 1.5.12.0, but after updating to 1.5.13.0 I couldn't reproduce the issue. It's now randomly started happening again, even if I use the unmodified parent theme.

If I switch over to the default XenForo theme then everything is fine.

**Comment by nsaneman** [comment]
I've just seen #92 and #58. I guess these are all the exact same bug?

**Comment by Ian-Hitt** [comment]
@nsaneman It is fixed, just not released. It will be available on 1.5.13.2 which should be released hopefully today.
