### ISSUE TITLE
Tactical - Sidebar Bug

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#104]
The first one is the sidebar (same bugg on pc): when you click on a navigation item, the icon for expanding the quick-links menu is invisible to the background. (See image)
When you scroll down on mobile, the top bar has a smooth animation, but when you scroll back up, it doesn't have always a smooth animation. (Tested it on safari, iphone 6s)
![img_0261](https://cloud.githubusercontent.com/assets/23287523/25440148/29380f7c-2a64-11e7-8a23-fe32162a52cc.png)

Ticket: https://admin.audent.io/tickets/7691

**Comment by nsaneman** [comment]
> The first one is the sidebar (same bugg on pc): when you click on a navigation item, the icon for expanding the quick-links menu is invisible to the background. (See image)

For Material the icon is missing in your official screenshots too.

https://xenforo.com/community/attachments/material-canvas-png.146415/

It was confusing a lot of my members, so I made it visible.

`.sidePanel .navTab .uix_icon {display: block;}`

**Comment by Ian-Hitt** [comment]
Fixed in Tactical/Tactical Light. Doesn't look like a Material bug

**Comment by Ian-Hitt** [comment]
<img width="478" alt="screen shot 2017-06-08 at 11 38 08 am" src="https://user-images.githubusercontent.com/15836384/26940075-f46f7b3e-4c3e-11e7-8853-03c29f1995cc.png">
