### ISSUE TITLE
Material - Sticky sidebar issues

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#105]
1. Go to your account preferences and disable the sticky sidebar.
2. Go back to the homepage and then toggle the width.

You'll see that the sidebar goes back to being sticky every time you change the width.

**Comment by nsaneman** [comment]
@dprock 
To replicate this you need your node tree to be longer than your sidebar.

**My enabled settings:**
Sticky Sidebar
Enabled Collapsible Sidebar
The default page with set to "fluid width"

As soon as you disable the sticky scroll bar, go to your node tree, scroll down and press the button to toggle the width. You'll see the sidebar drop to the bottom of the screen and it'll follow up as you scroll up.

**Comment by dprock** [comment]
I am honestly not able to replicate this. Would you be able to provide proof of this happening?

**Comment by nsaneman** [comment]
I'll setup a new test copy and install some screen capture software. So give me a little and I'll post a video or gif.

**Comment by nsaneman** [comment]
@dprock 
https://i.imgur.com/GFVcVyJ.gifv

- I toggle the setting and the page refreshes
- I scroll down and toggle the width
- I demonstrate that the sidebar acts as sticky after the pages width is toggled
- I refresh the page and show that it's back to normal
- I toggle the width again and show that it's back to acting sticky

**Comment by dprock** [comment]
Thank you so much, I will mark this as confirmed.

**Comment by kylerc** [comment]
Fixed on null demo now.  Will be in next release.
