### ISSUE TITLE
Material - Polls look bad on mobile

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#107]
![poll_1](https://cloud.githubusercontent.com/assets/26636634/25721469/1c570022-3100-11e7-847a-a5d810224247.png)
![poll_2](https://cloud.githubusercontent.com/assets/26636634/25721479/254cb6c2-3100-11e7-9341-3390cc45cc2d.png)

**Comment by nsaneman** [comment]
This fixes it.

```
.pollBlock .secondaryContent {padding: 10px;} /*allows both buttons to fit on 4" devices e.g. iPhone 5*/
.pollBlock .buttons .pollNotes {margin-bottom: 10px;} /*moves the text away from the buttons a little*/
.pollBlock .pollContent {padding-left: 0;} /*removes empty space to the left*/
.pollContent .question{display: block;} /*fixes the edit option and close date locations*/
```

You're welcome.

**Comment by Ian-Hitt** [comment]
Fixed styling for poll and for mobile.

**Comment by nsaneman** [comment]
@Ian-Hitt @dprock This says that it was fixed and it's tagged 1.5.13.1, but theres no changes for polls in the actual 1.5.13.1 release. The polls look exactly like the first image in this thread if I remove my code.

**Comment by nsaneman** [comment]
@Ian-Hitt @mikecreuzer Has this been fixed for 1.5.14.0?

**Comment by Ian-Hitt** [comment]
@nsaneman They were fixed in a soft release after the initial 1.5.13.0 release. Need to force re-install or wait for 1.5.14.0

**Comment by Ian-Hitt** [comment]
<img width="586" alt="screen shot 2017-06-06 at 12 43 58 pm" src="https://user-images.githubusercontent.com/15836384/26843444-df6c1d12-4ab5-11e7-878d-063279272422.png">

**Comment by nsaneman** [comment]
@Ian-Hitt Downloaded and installed via the UI.X theme installer.

![demo_image](https://user-images.githubusercontent.com/26636634/26843882-36c2e89a-4ae1-11e7-9a37-477befd361e0.png)

**Comment by nsaneman** [comment]
@Ian-Hitt And to be clear, that was a fresh installation. Nothing needed to be merged.

So it looks like your installer is giving people a different version to what you've got?
