### ISSUE TITLE
Material - Covers not displaying in the sidebar

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#115]
https://xenforo.com/community/threads/material-paid.125297/page-8#post-1150750

@mikecreuzer said that he wasn't able to track down the issue, yet I found the problem in under 60 seconds.

Whoever made changes to the sidebar in 1.5.13.0 deliberately changed the appearance. There's some conflicting css and someone even added ".visitorPanel .CoverImage {display: none !important;}", which is what's hiding the image.

**EXTRA.css fix**
```
.visitorPanel .avatar__headingBlock {
	background-color: transparent;
	padding: 0;
	margin: 0;
}
.CoverImage--overlay {
	padding: @uix_gutterWidthSmall;
	box-sizing: border-box;
}
.sidebar .visitorPanel .CoverImage {
	display: block !important;
	margin: -@uix_gutterWidthSmall -@uix_gutterWidthSmall @uix_gutterWidthSmall;
}
```

The TH demo page doesn't reflect the latest version of the Material theme with it's default settings. Maybe you guys should update it?

**Comment by nsaneman** [comment]
I've just noticed #108, which is a closed report for this issue. I don't know if a fix was found though, since there's no mention of it on the forums and on Wednesday Mike said that he couldn't track down the issue.

**Comment by Ian-Hitt** [comment]
This issue is fixed and will reflect in the upcoming update.
