### ISSUE TITLE
Material - Long usernames overlap in the sidebar

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#117]
If your account has a long username (the default max limit is 25 characters) then it'll overlap in the sidebar. You need to truncate it.

**Comment by Ian-Hitt** [comment]
@nsaneman Can you upload an image of this issue? They should just be breaking to the next line.

**Comment by nsaneman** [comment]
![username_sidebar](https://cloud.githubusercontent.com/assets/26636634/26694879/75f0e9a0-46f8-11e7-8202-777246171bbf.png)

@Ian-Hitt Done with Firefox.
