### ISSUE TITLE
Material - Quick navigation icon not always positioned correctly

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#122]
Disable the home tab and you might see this more often.

![quicknav_bug](https://cloud.githubusercontent.com/assets/26636634/26730245/c72b5a56-479f-11e7-927c-0fbb0f852e72.png)

**FIXED:**

```
@media (max-width:@maxResponsiveNarrowWidth) {
	.Responsive .breadBoxTop.withTopCtrl nav {
		display: block;
	}
}
```

![quicknav_fix](https://cloud.githubusercontent.com/assets/26636634/26730341/198caf2a-47a0-11e7-91ed-a9f20e642a0b.png)

**Comment by Ian-Hitt** [comment]
This is intentional responsive styling that fixes broken layouts when there is more content (like a top control.)

**Comment by nsaneman** [comment]
@Ian-Hitt
Technically couldn't you use an if statement in the template and then alter quick navs class? You'd then have CSS to handle both situations. And lets keep in mind that Material doesn't display anything next to the quick nav on mobile as everything gets put with navTabs.
