### ISSUE TITLE
Sticky Navigation

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xftheme-issues#143]
Already exists in XF2, but may need revising

- [ ] Sticky breakpoints

- [ ] Global Show Sticky on Scroll Up Only

- [ ] Minimum Height to Enable Sticky Scroll Up

- [ ] Scroll Sticky Trigger Distance

- [ ] Prevent Always 

- [ ] Add Selected Tab Sub-Links Sticky

- [ ] CSS sticky nav wrapper

**Comment by dprock** [comment]
Audentio/xf2theme-issues#27
