### ISSUE TITLE
By default, lets remove padding on links themselves on breadcrumb for desktop. For mobile we can add bg for chrome and padding

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xftheme-issues#175]
<img width="398" alt="screen shot 2017-07-25 at 11 40 22 am" src="https://user-images.githubusercontent.com/1217271/28583230-0d29547e-712e-11e7-9dcf-5ff622b83c1f.png">

This padding here is bugging me, and I think we can do without for desktop at least.

**Comment by JakeBooher** [comment]
Audentio/xf2theme-issues#3
