### ISSUE TITLE
I think the pageWidth wrap is oddly position in header/nav/userbar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xftheme-issues#192]
For example, try using width toggle

<img width="320" alt="screen shot 2017-07-25 at 12 11 24 pm" src="https://user-images.githubusercontent.com/1217271/28584453-733ec056-7132-11e7-8111-5293f654df15.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer No, its just the logo has giant white space

**Comment by mikecreuzer** [comment]
<img width="1915" alt="screen shot 2017-07-25 at 12 33 16 pm" src="https://user-images.githubusercontent.com/1217271/28585287-788d19d8-7135-11e7-86a0-45611d04fbb4.png">

**Comment by mikecreuzer** [comment]
<img width="1087" alt="screen shot 2017-07-25 at 12 39 22 pm" src="https://user-images.githubusercontent.com/1217271/28585596-4e7f475a-7136-11e7-942a-a00b74717342.png">

**Comment by JakeBooher** [comment]
Audentio/xf2theme-issues#12
