### ISSUE TITLE
UI.X - Color of text for conversations menu

### ISSUE THREAD

**Issue by daltonp** [Audentio/xftheme-issues#206]
It has been reported that the text color for the conversation menu is too dark. This includes the conversation titles and information (date, time, etc).
![screen shot 2017-10-03 at 10 23 33 am](https://user-images.githubusercontent.com/32306910/31133589-9bbb860c-a825-11e7-8648-73d63ec810df.png)

**Comment by mikecreuzer** [comment]
Supposed to be white iirc.
