### ISSUE TITLE
UI.X 2.0 - xen:container for extended footer (default to off for login/register-type views)

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#26]

**Comment by Ian-Hitt** [comment]
<xf:page option="hideExtendedFooter" value="1" />

**Comment by mikecreuzer** [comment]
By default I wonder if we should make decisions on what should be hidden on register/login views. I would say no welcome block, alerts, and probably no extended footer either. Should keep the normal footer.

**Comment by Ian-Hitt** [comment]
agreed

**Comment by Ian-Hitt** [comment]
any other pages you can think of? register/login. maybe search? error?
