### ISSUE TITLE
UI.X 2.0 - Beta releases option with the addon

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#43]

**Comment by Ian-Hitt** [comment]
What does this mean?

**Comment by kylerc** [comment]
Essentially, give users a toggle to be enrolled into the UI.X beta.  They'd get notifications for updates before all users did and would beta test the software for us for a few days before we roll it out for everyone.  The benefit for them is that they get bug fixes / new features first but the things would be less tested and less stable.

**Comment by dprock** [comment]
@kylerc Good idea, will give users a chance to suggest fixes and new features before the next release.

**Comment by Ian-Hitt** [comment]
wrong repo
