### ISSUE TITLE
UI.X Plugin – post #1133586 - Users Reporting no Notifications shown

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#55]
[Martok](https://xenforo.com/community/members/martok.46288/) wrote: ([view on xenforo.com](https://xenforo.com/community/threads/ui-x-paid.57944/page-340#post-1133586))
> Is anyone else no longer getting notifications in the ACP of the theme and add-on updates? Mine seemed to stop a little while ago (before I went https) so I don't think it's that and I haven't made any other changes.

**Comment by Ian-Hitt** [comment]
Need to update UI.X add-on
