### ISSUE TITLE
Material - Some bug issue found

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xftheme-issues#56]
Insert Quotes page are not showing button text: http://image.prntscr.com/image/d0208ae11b044f2b9bf3fcb2eee5d9a1.png

Page Navigation current page no are not visible: http://image.prntscr.com/image/981c2913735045e4a0a22d319a233593.png

**Comment by Ian-Hitt** [comment]
Unable to replicate page navigation styling issue. Likely due to a customization

**Comment by Ian-Hitt** [comment]
Both of these are due to customization. correct on all demos.
