### ISSUE TITLE
Material - Bug - Follow/Followers Backwards

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#58]
Following and Followers seem to be switched around - See images for more.
![1](https://cloud.githubusercontent.com/assets/23287523/23134274/cc377cdc-f759-11e6-97a0-c529bf283fde.png)
![2](https://cloud.githubusercontent.com/assets/23287523/23134275/cc3907d2-f759-11e6-9eab-ccdf0f3312b1.png)

**Comment by Ian-Hitt** [comment]
@dprock Am unable to replicate the issue.

**Comment by dprock** [comment]
I am not able to experience this issue again on the demo forums or my own forums. You may ignore this issue @Ian-Hitt as it may have been something that went wrong when the user installed the theme.
