### ISSUE TITLE
UI.X - Bug on devices with small screens

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#71]
There's a small bug on the forums causing the sidebar sections to protrude outside of the window when the content is long.
For example (Chrome / iPhone 5): https://cdn.jared.im/chrome_2017-03-20_16-04-56.png

As you can see, because of the long link, the contents of this sidebar clips outside of the forum and the text doesn't wrap.

Ticket Link: https://admin.audent.io/tickets/7658

**Comment by ellisonpatterson** [comment]
Due to text not being wrapped properly.
