### ISSUE TITLE
Material - Wrong tab color for warnings

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#74]
Give a user a warning and then look at the warning. The "Delete Warning" tab is black.

**Comment by dprock** [comment]
This is confirmed, please look over the links to see it in real time.

https://gyazo.com/166b68a199454650ce4b69ffcfbed880

https://gyazo.com/74f825b4284ffde4b0c1d069a13c5488

https://demo.themehouse.com/xf1/themes/index.php?members/demo.145/
