### ISSUE TITLE
Material - Mixed padding used in the sidebar

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#77]
Look at your account options from the sidebar (Chrome/iPhone 5). You'll see that the padding for 14 of the options is wrong.

**EXTRA.css fix:**
```
.sidePanel__blockLinksList a {padding: 10px;}
.sidePanel__blockLinksList .visibilityForm {padding: 10px;}
```

**Comment by nsaneman** [comment]
@dprock This was marked as invalid, but it's valid.

This is what it looks like without any modifications made to the theme.

https://s10.postimg.org/swz7zqc2x/sidebar_1.png
https://s2.postimg.org/823vzhxyh/sidebar_2.png

**Comment by Ian-Hitt** [comment]
Issue: CSS rule is not specific enough, being overwritten by default XF responsive styling
