### ISSUE TITLE
Material - Move up & down not accurate

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#79]
On a mobile device (Chrome/iPhone 5) select a posts checkbox to bring up the inline moderation tools and then press on either the up or down arrows.

This might be an XenForo issue in general. I'm not sure.

**Comment by dprock** [comment]
I have tested this, it works fine.

**Comment by nsaneman** [comment]
From a desktop view I can get it to work, but on my iPhone it's consistently not accurate.

Go to a thread with at least 19 replies and make sure they vary in size. Select to use inline moderation on the second post listed and then press the down arrow. Rather than going down to the next post it'll skip over 1 or 2.

**Comment by Ian-Hitt** [comment]
Confirmed this is an issue with XF
