### ISSUE TITLE
Material - The side panel icon is too small

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#86]
The \F35C icon is too small. Look at literally any Android apps hamburger button and you'll see that it's supposed to be larger.

It looks much better when set to 24px.

`.uix_icon-menu:before {font-size: 24px !important;}`

**Before:** https://s1.postimg.org/9yhneeqan/sidebar_icon.png

**After:** https://s1.postimg.org/d6m4rgckf/sidebar_icon_fixed.png

**Comment by Ian-Hitt** [comment]
Fixed, thanks
