### ISSUE TITLE
UI.X Sticky Navigation Issue

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#91]
https://admin.audent.io/tickets/7870

To replicate: when a popup is opened, and you scroll down before its closed again, and then scroll back up to initiate sticky, the arrow doesn't go away.

<img width="554" alt="screen shot 2017-04-17 at 9 24 17 am" src="https://cloud.githubusercontent.com/assets/23287523/25091876/d3fb5df8-2350-11e7-8a5a-2c4102610503.png">

**Comment by kylerc** [comment]
Fixed in `1.5.14.0`
