### ISSUE TITLE
Date & Year is covered and drop-down menu is bugged

### ISSUE THREAD

**Issue by dprock** [Audentio/xftheme-issues#96]
Please see image for more information, this has been confirmed in the demo forum.

![date-time-theme-bug](https://cloud.githubusercontent.com/assets/23287523/25199174/8096a45e-250f-11e7-9df1-88bf9825b463.png)

**Comment by Ian-Hitt** [comment]
This is a default theme issue, and is unfortunately intentional (even though its not always ideal.)

**Comment by Ian-Hitt** [comment]
<img width="484" alt="screen shot 2017-06-06 at 10 18 16 am" src="https://user-images.githubusercontent.com/15836384/26836815-7b26377a-4aa1-11e7-8ad0-0d38fb6d8d21.png">
