### ISSUE TITLE
Material - Sidebar overlaps on mobile

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#97]
![new_posts_bug](https://cloud.githubusercontent.com/assets/26636634/25314369/22050568-2832-11e7-8cf5-866ebae1984d.png)

It always happens when a thread has a long(ish) title.

**Comment by dprock** [comment]
I have been able to confirm this on the **iPhone 5** only. Other iPhones and Galaxies seem to work fine with the long titles.

**Comment by nsaneman** [comment]
@dprock I can actually get it to do it on all of the devices apart from the iPads. All I need to do is set a long enough time.

My Sony Xperia Z1 (5.0 inches) is often displaying the issue, so it's going to be a common problem.

**Comment by Ian-Hitt** [comment]
Fixed, thanks
