### ISSUE TITLE
Material - Bold text is blurry

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xftheme-issues#99]
Any bold text is blurry, especially if you're using Chrome on Windows. The reason is that Roboto Bold starts at 700 and you don't include it.

Add 700 to the Google fonts and then look at a post with a good amount of bold text. Compare it to an unmodified version of the theme and you'll notice a difference if you look closely at the letters.

**Comment by Ian-Hitt** [comment]
@nsaneman This reason for this is that because Google's Material spec suggests using the semi-bold 500 value for bold text. We also suggest, and only use this value. You can add it easy enough on Style Properties > Typography if you would like to use it.

**Comment by nsaneman** [comment]
@Ian-Hitt The problem is that although semi-bold works in some specific areas, it doesn't work for posts or whenever a plugin uses bold. You'd get a horrible blurry looking font displayed instead.

When you add 700 post content and plugins look **much** better. Everything that uses 500 still works too, so IMO there's no harm in adding 700. It's got to be better than having blurry fonts.
